import json

divisions = [
    ("A", "01", "Crop and animal production, hunting and related service activities"),
    ("A", "02", "Forestry and logging"),
    ("A", "03", "Fishing and aquaculture"),
    ("B", "05", "Mining of coal and lignite"),
    ("B", "06", "Extraction of crude petroleum and natural gas"),
    ("B", "07", "Mining of metal ores"),
    ("B", "08", "Other mining and quarrying"),
    ("B", "09", "Mining support service activities"),
    ("C", "10", "Manufacture of food products"),
    ("C", "11", "Manufacture of beverages"),
    ("C", "12", "Manufacture of tobacco products"),
    ("C", "13", "Manufacture of textiles"),
    ("C", "14", "Manufacture of wearing apparel"),
    ("C", "15", "Manufacture of leather and related products"),
    ("C", "16", "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials"),
    ("C", "17", "Manufacture of paper and paper products"),
    ("C", "18", "Printing and reproduction of recorded media"),
    ("C", "19", "Manufacture of coke and refined petroleum products"),
    ("C", "20", "Manufacture of chemicals and chemical products"),
    ("C", "21", "Manufacture of basic pharmaceutical products and pharmaceutical preparations"),
    ("C", "22", "Manufacture of rubber and plastic products"),
    ("C", "23", "Manufacture of other non-metallic mineral products"),
    ("C", "24", "Manufacture of basic metals"),
    ("C", "25", "Manufacture of fabricated metal products, except machinery and equipment"),
    ("C", "26", "Manufacture of computer, electronic and optical products"),
    ("C", "27", "Manufacture of electrical equipment"),
    ("C", "28", "Manufacture of machinery and equipment n.e.c."),
    ("C", "29", "Manufacture of motor vehicles, trailers and semi-trailers"),
    ("C", "30", "Manufacture of other transport equipment"),
    ("C", "31", "Manufacture of furniture"),
    ("C", "32", "Other manufacturing"),
    ("C", "33", "Repair, maintenance and installation of machinery and equipment"),
    ("D", "35", "Electricity, gas, steam and air conditioning supply"),
    ("E", "36", "Water collection, treatment and supply"),
    ("E", "37", "Sewerage"),
    ("E", "38", "Waste collection, treatment and disposal, and recovery activities"),
    ("E", "39", "Remediation and other waste management service activities"),
    ("F", "41", "Construction of residential and non-residential buildings"),
    ("F", "42", "Civil engineering"),
    ("F", "43", "Specialized construction activities"),
    ("G", "46", "Wholesale trade"),
    ("G", "47", "Retail trade"),
    ("H", "49", "Land transport and transport via pipelines"),
    ("H", "50", "Water transport"),
    ("H", "51", "Air transport"),
    ("H", "52", "Warehousing and support activities for transportation"),
    ("H", "53", "Postal and courier activities"),
    ("I", "55", "Accommodation"),
    ("I", "56", "Food and beverage service activities"),
    ("J", "58", "Publishing activities"),
    ("J", "59", "Motion picture, video and television programme production, sound recording and music publishing activities"),
    ("J", "60", "Programming, broadcasting, news agency and other content distribution activities"),
    ("K", "61", "Telecommunications"),
    ("K", "62", "Computer programming, consultancy and related activities"),
    ("K", "63", "Computing infrastructure, data processing, hosting, and other information service activities"),
    ("L", "64", "Financial service activities, except insurance and pension funding"),
    ("L", "65", "Insurance, reinsurance and pension funding, except compulsory social security"),
    ("L", "66", "Activities auxiliary to financial service and insurance activities"),
    ("M", "68", "Real estate activities"),
    ("N", "69", "Legal and accounting activities"),
    ("N", "70", "Activities of head offices; management consultancy activities"),
    ("N", "71", "Architectural and engineering activities; technical testing and analysis"),
    ("N", "72", "Scientific research and development "),
    ("N", "73", "Activities of advertising, market research and public relations"),
    ("N", "74", "Other professional, scientific and technical activities"),
    ("N", "75", "Veterinary activities "),
    ("O", "77", "Rental and leasing activities"),
    ("O", "78", "Employment activities"),
    ("O", "79", "Travel agency, tour operator, and other travel related activities"),
    ("O", "80", "Investigation and security activities"),
    ("O", "81", "Services to buildings and landscape activities"),
    ("O", "82", "Office administrative, office support and other business support activities"),
    ("P", "84", "Public administration and defence; compulsory social security"),
    ("Q", "85", "Education"),
    ("R", "86", "Human health activities"),
    ("R", "87", "Residential care activities"),
    ("R", "88", "Social work activities without accommodation "),
    ("S", "90", "Arts creation and performing arts activities"),
    ("S", "91", "Library, archives, museum and other cultural activities "),
    ("S", "92", "Gambling and betting activities"),
    ("S", "93", "Sports activities and amusement and recreation activities"),
    ("T", "94", "Activities of membership organizations"),
    ("T", "95", "Repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles"),
    ("T", "96", "Personal service activities"),
    ("U", "97", "Activities of households as employers of domestic personnel"),
    ("U", "98", "Undifferentiated goods- and services-producing activities of private households for own use"),
    ("V", "99", "Activities of extraterritorial organizations and bodies "),
]

EXTRA_HINTS = {
    "A-01": ["farming", "agriculture", "crop", "livestock", "farmer", "rural", "agricultural"],
    "A-02": ["forestry", "logging", "forest", "timber"],
    "A-03": ["fishing", "fishery", "aquaculture", "fisher"],
    "B-08": ["mining", "quarry", "mineral"],
    "C-10": ["food production", "food manufacturing"],
    "C-21": ["pharmaceutical", "medicine production"],
    "C-26": ["electronics", "semiconductor"],
    "D-35": ["electricity", "renewable energy", "solar", "wind power", "energy transition", "power supply"],
    "E-36": ["water supply", "drinking water"],
    "E-38": ["waste management", "recycling"],
    "F-41": ["construction", "building", "housing construction"],
    "G-47": ["retail", "shopping", "consumer", "market trade"],
    "H-49": ["transport", "mobility", "traffic", "railway", "commuting"],
    "H-51": ["aviation", "airline", "air travel"],
    "I-55": ["hotel", "tourism", "accommodation", "hospitality"],
    "I-56": ["restaurant", "food service", "catering"],
    "J-58": ["publishing", "books"],
    "J-59": ["film", "cinema", "video", "documentary", "music"],
    "J-60": ["broadcasting", "radio", "television", "journalism", "news"],
    "K-61": ["telecommunications", "telecom", "mobile phone"],
    "K-62": ["software", "programming", "information technology", "app development", "coding"],
    "K-63": ["data processing", "internet", "social media", "online platform", "web hosting", "artificial intelligence", "computing"],
    "L-64": ["banking", "finance", "credit", "loan", "investment", "financial"],
    "L-65": ["insurance", "pension fund", "reinsurance"],
    "M-68": ["real estate", "property", "housing market"],
    "N-69": ["legal", "law", "court", "justice", "lawyer", "litigation", "accounting"],
    "N-70": ["management consulting", "business strategy"],
    "N-71": ["architecture", "engineering"],
    "N-72": ["research", "scientific", "science", "experiment", "innovation", "methodology", "laboratory"],
    "N-73": ["advertising", "marketing", "market research", "public relations"],
    "N-75": ["veterinary", "animal health"],
    "O-78": ["employment", "recruitment", "labour market", "job", "work", "workplace", "career", "occupation", "labor"],
    "O-80": ["security service", "investigation", "surveillance"],
    "P-84": ["government", "public administration", "policy", "politics", "election", "democracy", "governance", "public sector", "citizenship", "war", "conflict", "military", "peace", "human rights", "migration", "refugee", "nationalism", "state"],
    "Q-85": ["education", "school", "teaching", "student", "learning", "university", "teacher", "classroom", "pedagogy", "literacy", "curriculum", "childhood", "adolescent", "academic"],
    "R-86": ["health", "hospital", "medical", "patient", "disease", "clinical", "healthcare", "medicine", "nursing", "doctor", "mental health", "illness", "therapy", "covid", "pandemic", "wellbeing", "pregnancy", "psychological"],
    "R-87": ["care home", "nursing home", "residential care", "elderly care"],
    "R-88": ["social work", "welfare", "social service", "poverty", "homeless", "vulnerable", "disability", "gender", "feminism", "inequality", "discrimination", "minority", "family", "youth", "ageing", "violence", "abuse", "ethnic"],
    "S-90": ["art", "music", "theatre", "creative", "culture", "cultural", "artist", "performance", "literature"],
    "S-91": ["library", "museum", "archive", "heritage"],
    "S-93": ["sport", "recreation", "leisure", "exercise", "fitness", "athletics"],
    "T-94": ["religion", "religious", "church", "political party", "union", "association", "community organization", "ngo", "social movement", "activism"],
    "T-96": ["personal service", "lifestyle"],
    "U-97": ["domestic worker", "household employment"],
    "V-99": ["united nations", "international organization", "diplomacy"],
}

# Finnish and Norwegian words
MULTI_HINTS = {
    "A-01": ["maatalous","maanviljely","landbruk","jordbruk","gård"],
    "A-03": ["kalastus","fiske","fiskeri"],
    "D-35": ["energia","sähkö","energi","strøm","fornybar"],
    "E-36": ["vesi","vann","drikkevann"],
    "E-38": ["jäte","kierrätys","avfall","gjenvinning","ydinjäte","kjernefysisk avfall"],
    "H-49": ["liikenne","transportti","transport","samferdsel","trafikk"],
    "J-59": ["elokuva","media","film","video","musikk","musiikki"],
    "J-60": ["radio","televisio","kringkasting","uutiset","nyheter"],
    "K-63": ["internet","sosiaalinen media","sosiale medier","nettbrett","digitaalinen"],
    "L-64": ["pankki","rahoitus","bank","finans","økonomi","talous"],
    "N-69": ["laki","oikeus","lov","juridisk","domstol","tuomioistuin"],
    "N-72": ["tutkimus","tiede","forskning","vitenskap","tieteellinen"],
    "O-78": ["työ","työllisyys","ammatti","arbeid","sysselsetting","yrke","arbeidsliv","työelämä"],
    "P-84": ["politiikka","hallinto","vaalit","demokratia","valtio","politikk","forvaltning","valg","demokrati","stat","kunta","kommune","julkishallinto","offentlig"],
    "Q-85": ["koulutus","koulu","opetus","oppilas","opiskelija","yliopisto","opettaja","kasvatus","utdanning","skole","undervisning","elev","student","universitet","lærer","opplæring"],
    "R-86": ["terveys","sairaala","potilas","lääkäri","sairaus","hoito","mielenterveys","hyvinvointi","helse","sykehus","pasient","lege","sykdom","behandling","psykisk helse","velvære"],
    "R-88": ["sosiaalityö","hyvinvointi","köyhyys","vammaisuus","sukupuoli","tasa-arvo","perhe","nuoret","maahanmuuttaja","sosialt arbeid","velferd","fattigdom","funksjonshemming","kjønn","likestilling","familie","ungdom","innvandrer"],
    "S-90": ["taide","musiikki","teatteri","kulttuuri","taiteilija","kirjallisuus","kunst","musikk","teater","kultur","kunstner","litteratur"],
    "S-91": ["kirjasto","museo","arkisto","perintö","kulttuuriperintö","bibliotek","museum","arkiv","kulturarv"],
    "S-93": ["urheilu","liikunta","sport","idrett","trening"],
    "T-94": ["uskonto","kirkko","yhdistys","järjestö","religion","kirke","forening","organisasjon"],
}

junk_words = {"and", "other", "activities", "manufacture", "related", "except",
              "service", "services", "products", "production", "n.e.c", "the",
              "of", "for", "with", "without", "auxiliary", "compulsory"}

final_map = {}
for section, div_num, title in divisions:
    code = f"{section}-{div_num}"
    words = [w.lower().strip(",;") for w in title.split()
             if len(w) > 4 and w.lower() not in junk_words]
    extra_en = EXTRA_HINTS.get(code, [])
    extra_ml = MULTI_HINTS.get(code, [])
    all_keywords = set(words + extra_en + extra_ml)

    final_map[code] = {
        "section": section,
        "div": div_num,
        "title": title,
        "keywords": sorted(all_keywords)
    }

with open("isic_keywords_map.json", "w", encoding="utf-8") as f:
    json.dump(final_map, f, indent=2, ensure_ascii=False)

print(f"Keyword mapping for {len(final_map)} divisions")